# Generated by Django 3.0.8 on 2021-01-21 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='collegeName',
        ),
    ]
