# Generated by Django 3.0.8 on 2021-01-21 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_remove_student_collegename'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='courseName',
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='courseName',
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='subjectName',
        ),
    ]
