# Generated by Django 3.0.8 on 2021-01-22 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_auto_20210121_1846'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faculty',
            name='collegeName',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='courseName',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='subjectName',
        ),
    ]
